baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://bastibond.github.io/visitenkarte" # the base hostname & protocol for your site.
title: ".de"

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: "https://github.com/bastibond"  #your github url here.

twitter: "https://"  #Add your twitter url here.
facebook: "https://"
homepage: "Http://.de"
youtube: "https://www.youtube.com/channel/UC5jCUQ6IPHtQP5r4y9byCqA"
email: ".de"

#disqus comment
disqus:
    shortname: "test" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
     - jekyll-sitemap
     - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



theme: jekyll-theme-cayman
